name: Build NVDA

description: 'Builds NVDA'

runs:
  using: "composite"

  steps:
    - name: Checkout NVDA
      uses: actions/checkout@v4
      with:
        repository: 'nvaccess/nvda'
        submodules: true
        ref: ${{ github.ref }}
    - name: Install dependencies
      id: setupPython
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: x86
        cache: pipenv
        cache-dependency-path: |
          requirements.txt
    - name: Exit if dependencies are cached
      if: ${{ steps.setupPython.outputs.cache-hit == 'true' }}
      run: exit 0
      shell: cmd
    - name: Set version variables
      run: powershell.exe ci/scripts/setBuildVersionVars.ps1
      shell: cmd
    - name: Set scons args
      run: powershell.exe ci/scripts/setSconsArgs.ps1
      shell: cmd
    - name: Prepare source code
      run: scons source %sconsArgs% --all-cores
      shell: cmd
